#!/bin/bash

echo "Saisir une note"
read note

moy=0
i=0

if [ $note = "q" ]
then
let note=-1
fi


while [ "$note" -ge 0 ]
do

if [ $note -ge 16 -a $note -le 20 ]
then
echo "tres bien"
elif [ $note -ge 14 -a $note -lt 16 ]
then
echo "bien"
elif [ $note -ge 12 -a $note -lt 14 ]
then
echo "assez bien"
elif [ $note -ge 10 -a $note -lt 12 ]
then
echo "moyen"
elif [ $note -lt 10 ]
then
echo "insuffisant"
fi

let moy=moy+note
let i=i+1

echo "Saisir une nouvelle note ou q pour quitter"
read note

if [ "$note" = "q" ]
then
break
fi

done

if [ $i -ne 0 ]
then
let moy=moy/i
fi

echo "La moyenne est $moy"

